### ISSUE TITLE
Generating with pop 909 dataset

### ISSUE THREAD

**Issue by Wayne-wonderai** [billyblu2000/Chorderator#5]
I'm trying `demo.py `using one of data in pop909  dataset (only keep melody track), but it didn't work, full message as below.
The file is as attach, can you help me to check whats the problem?
Thanks!

```/mnt/e2203fdf-08ef-4193-9c98-04fcd3f8df26/AccoMontage2/chorderator/utils/utils.py:24: UserWarning: Could not import FluidSynth, audio formats writing disabled
  warnings.warn('Could not import FluidSynth, audio formats writing disabled')
/mnt/e2203fdf-08ef-4193-9c98-04fcd3f8df26/AccoMontage2/chorderator/core.py:238: UserWarning: Meter auto set to 4/4/. Please set meter if this is not your expectation
  warnings.warn('Meter auto set to 4/4/. Please set meter if this is not your expectation')
/mnt/e2203fdf-08ef-4193-9c98-04fcd3f8df26/AccoMontage2/chorderator/core.py:241: UserWarning: Mode auto set to major. Please set mode if this is not your expectation
  warnings.warn('Mode auto set to major. Please set mode if this is not your expectation')
@Chorderator 2022-11-01 16:52:42,695 - INFO -  start read progressions from dict 
@Chorderator 2022-11-01 16:52:48,565 - INFO -  read progressions done 
@Chorderator 2022-11-01 16:52:48,566 - INFO -  start read progression library from source_base.pnt 
@Chorderator 2022-11-01 16:52:55,625 - INFO -  read library done 
@Chorderator 2022-11-01 16:52:55,626 - WARNING -  Pre-processing... 
{'tonic': 'G', 'meter': '4/4', 'mode': 'maj', 'pos': ['x', 'x', 'x', 'x'], 'tempo': 61.000034566686246, 'unit': 0.24590150000000002}
Traceback (most recent call last):
  File "demo.py", line 15, in <module>
    cdt.generate_save(demo_name + '_output_results')
  File "/mnt/e2203fdf-08ef-4193-9c98-04fcd3f8df26/AccoMontage2/chorderator/interaction.py", line 91, in generate_save
    return _core.generate_save(output_name=output_name, task=task, log=log, wav=wav, **kwargs)
  File "/mnt/e2203fdf-08ef-4193-9c98-04fcd3f8df26/AccoMontage2/chorderator/core.py", line 391, in generate_save
    gen, chord_gen, gen_log = self.generate(cut_in=cut_in, cut_in_arg=cut_in_arg, with_texture=with_texture,
  File "/mnt/e2203fdf-08ef-4193-9c98-04fcd3f8df26/AccoMontage2/chorderator/core.py", line 361, in generate
    gen = self.run(cut_in, cut_in_arg, with_texture, **kwargs)
  File "/mnt/e2203fdf-08ef-4193-9c98-04fcd3f8df26/AccoMontage2/chorderator/core.py", line 275, in run
    self.pipeline.send_in(self.midi_path,
  File "/mnt/e2203fdf-08ef-4193-9c98-04fcd3f8df26/AccoMontage2/chorderator/utils/pipeline.py", line 49, in send_in
    self.melo, splited_melo, self.meta = self.__preprocess(midi_path, **kwargs)
  File "/mnt/e2203fdf-08ef-4193-9c98-04fcd3f8df26/AccoMontage2/chorderator/utils/pipeline.py", line 71, in __preprocess
    return processor.get()
  File "/mnt/e2203fdf-08ef-4193-9c98-04fcd3f8df26/AccoMontage2/chorderator/utils/models/PreProcessor.py", line 40, in get
    handle_exception(312)
  File "/mnt/e2203fdf-08ef-4193-9c98-04fcd3f8df26/AccoMontage2/chorderator/utils/excp.py", line 59, in handle_exception
    raise ValueError('[Error {e}] '.format(e=code) + msg + website)
ValueError: [Error 312] Phrase length not accepted. Up to the current version, only the following length is supported: 4, 8, 12, 16, 24, 32. For more information, please visit https://...com.```


[melody.zip](https://github.com/billyblu2000/AccoMontage2/files/9908706/melody.zip)

**Comment by Wayne-wonderai** [comment]
Have fixed the problem by change `set_segmentation` config, thx
